### ISSUE TITLE
Add Docker Toolbox information

### ISSUE THREAD

**Issue by jiv-e** [dockerizedrupal/drupalcamp-baltics-2015#1]
You mentioned the new Docker Toolbox on your live presentation. It would be nice to have it also in the repo (if you have time to add it).

**Comment by viljaste** [comment]
Hey, do you mean how to work with Drupal using Docker Toolbox?

**Comment by jiv-e** [comment]
I just remember that you mentioned that in the presentation but it's not added here.

**Comment by viljaste** [comment]
The part about Docker Toolbox is actually there, you can find it on the sixth slide.

**Comment by jiv-e** [comment]
You are correct! Strange, I thought I did a page search and tried to find it. Must have been some kind of short term blindness. Thanks again for a great presentation!
